---

- hosts: local
  vars_files:
    - group_vars/all.yml

  roles:

    - common       # List of essential packages
    - design       # Design pack
    #- latex        # Latex and ide texmaker
    - nodejs
    - browsers
    - dev
    - multimedia
    - virtualization
    - users
    - awesome
    - communication
    #- filesharing
    - games
