---
- name: Install Teams
  shell: flatpak install com.microsoft.Teams -y

- name: Install Anydesk
  shell: flatpak install com.anydesk.Anydesk -y


- name: Install Slack
  community.general.snap:
    name: slack
    classic: yes

- name: Install Discord
  community.general.snap:
    name: discord
    classic: yes

