---
- name: remove stuff
  apt:
    name:
      - virtualbox
      - vagrant

- name: Virtualization | Install lists packages
  apt:
    name:
      - docker
      - docker-compose
      - binutils
      - gcc
      - make
      - cmake
      - golang-go
      - patch
      - gnome-boxes
      - virt-manager
      - cockpit
      - cockpit-machines
      - cockpit-bridge
      - cockpit-networkmanager
      - cockpit-packagekit
      - cockpit-system
      - cockpit-podman
      - cockpit-storaged
    state: latest

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: yes


- name: Install distrobox
  shell:  curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
