---
- name: Install X11 libs
  apt:
    name:
      - libx11-dev
      - libxcursor-dev 
      - libxrandr-dev
      - libxinerama-dev
      - libxi-dev
      - libgl1-mesa-dev
      - g++
      - libsdl2-gfx-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libsdl2-dev
      - libxxf86vm-dev
      - intltool
      - libglib2.0-dev
      - libtool
      - fonts-firacode
    state: present

- name: Install "Snap"
  apt: name=snapd state=latest 

- name: Enable "Snap"
  service: name=snapd state=started enabled=yes

- name: Install "Android Studio" with option --classic
  snap:
    name: android-studio
    classic: yes

- name: Install "pycharm-professional" with option --classic
  community.general.snap:
    name: pycharm-professional
    classic: yes

- name: Install "vscode" with option --classic
  community.general.snap:
    name: code
    classic: yes

- name: install "insomnia" 
  community.general.snap:
    name: insomnia
    state: present

- name: Install "postbird" 
  community.general.snap:
    name: postbird

- name: Install "dbeaver" 
  community.general.snap:
    name: dbeaver-ce       

- name: Install "arduino"
  apt:
    name: arduino

- name: Install "micro"
  apt:
    name: micro

- name: Install "zeal"
  apt:
    name: zeal

